#
# Generated by dumpDCWorkflow.py written by Sebastien Bigaret
# Original workflow id/title: openplans_teamspace_workflow/OpenPlans Project Workflow
# Date: 2007/02/09 20:02:13.530 US/Pacific
#
# WARNING: this dumps does NOT contain any scripts you might have added to
# the workflow, IT IS YOUR RESPONSABILITY TO MAKE BACKUPS FOR THESE SCRIPTS.
#
# No script detected in this workflow
#
"""
Programmatically create a workflow type.
"""
__version__ = "$Id: dumpDCWorkflow.py 31159 2006-09-28 21:40:48Z encolpe $"

from Products.CMFCore.WorkflowTool import addWorkflowFactory
from Products.DCWorkflow.DCWorkflow import DCWorkflowDefinition
from Products.PythonScripts.PythonScript import PythonScript
from Products.ExternalMethod.ExternalMethod import ExternalMethod

def setup_openplans_teamspace_workflow(wf):
    """Setup the workflow
    """
    wf.setProperties(title='OpenPlans Project Workflow')

    for s in ('closed', 'medium', 'open'):
        wf.states.addState(s)
    for t in ('close', 'medium', 'open'):
        wf.transitions.addTransition(t)
    for v in ('action', 'actor', 'comments', 'review_history', 'time'):
        wf.variables.addVariable(v)
    for l in ():
        wf.worklists.addWorklist(l)
    for p in ('Access contents information',
              'Modify portal content',
              'View',
              'List folder contents',
              'Delete objects',
              'CMFEditions: Revert to previous versions',
              'OpenPlans: Add OpenPage',
              'Copy or Move'):
        wf.addManagedPermission(p)

    # Initial State
    wf.states.setInitialState('open')

    # State Initialization
    sdef = wf.states['closed']
    sdef.setProperties(title='Closed',
                       description='',
                       transitions=('medium', 'open'))
    sdef.setPermission('Access contents information', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Modify portal content', 0,
                       ['Manager', 'Owner', 'ProjectAdmin', 'ProjectContentMgr', 'Reviewer'])
    sdef.setPermission('View', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('List folder contents', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Delete objects', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('CMFEditions: Revert to previous versions', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('OpenPlans: Add OpenPage', 1,
                       [])
    sdef.setPermission('Copy or Move', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])

    sdef = wf.states['medium']
    sdef.setProperties(title='Medium',
                       description='',
                       transitions=('close', 'open'))
    sdef.setPermission('Access contents information', 0,
                       ['Anonymous',
                       'Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Modify portal content', 0,
                       ['Manager', 'Owner', 'ProjectAdmin', 'ProjectContentMgr', 'Reviewer'])
    sdef.setPermission('View', 0,
                       ['Anonymous',
                       'Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('List folder contents', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Delete objects', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('CMFEditions: Revert to previous versions', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('OpenPlans: Add OpenPage', 1,
                       [])
    sdef.setPermission('Copy or Move', 0,
                       ['Manager',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])

    sdef = wf.states['open']
    sdef.setProperties(title='Open',
                       description='',
                       transitions=('close', 'medium'))
    sdef.setPermission('Access contents information', 0,
                       ['Anonymous',
                       'Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Modify portal content', 0,
                       ['Manager', 'Owner', 'ProjectAdmin', 'ProjectContentMgr', 'Reviewer'])
    sdef.setPermission('View', 0,
                       ['Anonymous',
                       'Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('List folder contents', 0,
                       ['Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Delete objects', 0,
                       ['Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('CMFEditions: Revert to previous versions', 0,
                       ['Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('OpenPlans: Add OpenPage', 0,
                       ['Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])
    sdef.setPermission('Copy or Move', 0,
                       ['Authenticated',
                       'Manager',
                       'Member',
                       'Owner',
                       'ProjectAdmin',
                       'ProjectContentMgr',
                       'ProjectMember',
                       'Reviewer'])

    # Transition Initialization
    tdef = wf.transitions['close']
    tdef.setProperties(title='Close',
                       description='',
                       new_state_id='closed',
                       trigger_type=1,
                       script_name='',
                       after_script_name='',
                       actbox_name='Close',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_permissions': 'Modify portal content'},
                       )

    tdef = wf.transitions['medium']
    tdef.setProperties(title='Medium',
                       description='',
                       new_state_id='medium',
                       trigger_type=1,
                       script_name='',
                       after_script_name='',
                       actbox_name='Medium',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_permissions': 'Modify portal content'},
                       )

    tdef = wf.transitions['open']
    tdef.setProperties(title='Open',
                       description='',
                       new_state_id='open',
                       trigger_type=1,
                       script_name='',
                       after_script_name='',
                       actbox_name='Open',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_permissions': 'Modify portal content'},
                       )

    # State Variable
    wf.variables.setStateVar('review_state')

    # Variable Initialization
    vdef = wf.variables['action']
    vdef.setProperties(description='The last transition',
                       default_value='',
                       default_expr='transition/getId|nothing',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['actor']
    vdef.setProperties(description='The ID of the user who performed the last transition',
                       default_value='',
                       default_expr='user/getId',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['comments']
    vdef.setProperties(description='Comments about the last transition',
                       default_value='',
                       default_expr="python:state_change.kwargs.get('comment', '')",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['review_history']
    vdef.setProperties(description='Provides access to workflow history',
                       default_value='',
                       default_expr='state_change/getHistory',
                       for_catalog=0,
                       for_status=0,
                       update_always=0,
                       props={'guard_permissions': 'Request review; Review portal content'})

    vdef = wf.variables['time']
    vdef.setProperties(description='Time of the last transition',
                       default_value='',
                       default_expr='state_change/getDateTime',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    # Worklist Initialization
def create_openplans_teamspace_workflow(id):
    """Create, setup and return the workflow.
    """
    ob = DCWorkflowDefinition(id)
    setup_openplans_teamspace_workflow(ob)
    return ob

addWorkflowFactory(create_openplans_teamspace_workflow,
                   id='openplans_teamspace_workflow',
                   title='OpenPlans Project Workflow')
